version: '3'
services:
  web:
    image: trzl/portfolio:pyt-react.1
    container_name: pyt-react
    restart: unless-stopped
    expose:
      - "80"
      - "443"
    environment:
      VIRTUAL_HOST: pytdance.tbrownkcdev.com
      LETSENCRYPT_HOST: pytdance.tbrownkcdev.com
      LETSENCRYPT_EMAIL: brownty47@gmail.com
networks:
  default:
    external:
      name: webproxy
